apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-config
  namespace: kube-system
data:
# change log group name!!!
  fluent-bit.conf: |
    [SERVICE]
        Flush         1
        Log_Level     info
        Parsers_File  parsers.conf

    [INPUT]
        Name          tail
        Path          /var/log/containers/deployment-nginx*.log
        Tag           nginx.*
        DB            /var/log/flb_kube.db
        Mem_Buf_Limit 5MB
        Skip_Long_Lines On

    [FILTER]
        Name          kubernetes
        Match         nginx.*
        Kube_Tag_Prefix nginx
        Merge_Log     On
        K8S-Logging.Parser On
        K8S-Logging.Exclude Off

    [OUTPUT]
        Name          cloudwatch
        Match         nginx.*
        region        ap-northeast-2
        log_group_name mhsong-eks-app-log
        log_stream_prefix nginx
        auto_create_group true
  parsers.conf: |
    [PARSER]
        Name        json
        Format      json
        Time_Key    time
        Time_Format %Y-%m-%dT%H:%M:%S
        Decode_Field_As escaped_utf8 log
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fluentbit-sa
  namespace: kube-system
  annotations:
  # change me!
    eks.amazonaws.com/role-arn: arn:aws:iam::694448341573:role/mhsong-fluentbit-sa-role
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluent-bit
  namespace: kube-system
  labels:
    k8s-app: fluent-bit
spec:
  selector:
    matchLabels:
      k8s-app: fluent-bit
  template:
    metadata:
      labels:
        k8s-app: fluent-bit
    spec:
      serviceAccountName: fluentbit-sa
      containers:
      - name: fluent-bit
        image: fluent/fluent-bit:latest
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 100Mi
        volumeMounts:
        - name: varlogcontainers
          mountPath: /var/log/containers
          readOnly: true
        - name: config
          mountPath: /fluent-bit/etc/
      volumes:
      - name: varlogcontainers
        hostPath:
          path: /var/log/containers
      - name: config
        configMap:
          name: fluent-bit-config
