---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring-test
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: monitoring-test
  name: deployment-monitoring
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: app-monitoring
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: app-monitoring
    spec:
      containers:
      - image: nginx:latest
        imagePullPolicy: Always
        name: app-monitoring
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
---
apiVersion: v1
kind: Service
metadata:
  namespace: monitoring-test
  name: service-monitoring
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  type: NodePort
  selector:
    app.kubernetes.io/name: app-monitoring
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: monitoring-test
  name: ingress-monitoring
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: service-monitoring
              port:
                number: 80
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: nginx-hpa
  namespace: monitoring-test
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: deployment-monitoring
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
