apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: kube-system
  name: deployment-fastapi
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: app-fastapi
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: app-fastapi
    spec:
      containers:
      # Change your account id
      - image: 694448341573.dkr.ecr.ap-northeast-2.amazonaws.com/prom-test:latest
        imagePullPolicy: Always
        name: app-fastapi
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  namespace: kube-system
  name: service-fastapi
spec:
  ports:
    - name: fastapi
      port: 8000
      targetPort: 8000
      protocol: TCP
  type: NodePort
  selector:
    app.kubernetes.io/name: app-fastapi
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: kube-system
  name: ingress-fastapi
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: service-fastapi
              port:
                number: 8000