name: CI/CD

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'manifests/**'

env:
  IMAGE_TAG: ${{ github.sha }}

jobs:
  build-and-push:
    name: Build and Push to ECR
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Log in to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and Push Docker Image
        run: |
          cd code
          docker build -t ${{ secrets.ECR_REPOSITORY }}:$IMAGE_TAG .
          docker push ${{ secrets.ECR_REPOSITORY }}:$IMAGE_TAG

  deploy-with-argocd:
    name: Deploy to Kubernetes via ArgoCD
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Update Kubernetes Manifests with New Image
        run: |
          sed -i "s|image: .*|image: ${{ secrets.ECR_REPOSITORY }}:$IMAGE_TAG|g" manifests/2_deployment.yaml

      - name: Commit and Push Changes
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add manifests/2_deployment.yaml
          git commit -m "Update image to ${{ secrets.ECR_REPOSITORY }}:$IMAGE_TAG"
          git push origin main